.Dd November 05, 2015
.Dt TROP 1
.Os
.Sh NAME
.Nm trop
.Nd transmission-remote operations
.Sh SYNOPSIS
.Nm
.Op Fl h Ar HOST:PORT
.Op Fl a Ar USER:PASS
.Ar options ...
.Sh DESCRIPTION
.Nm
is a shell script for Unix-like systems designed to make interaction with
.Xr transmission-remote 1
easier.
It is written in pure POSIX Bourne shell and AWK;
This allows
.Nm
to be used on nearly any Unix system that transmission can be built on.
A nice feature of
.Nm
is the ability to save the default host and authentication information in the
.Pa tropriv.sh
file.
That way you don't have to supply this information on the command-line every time you need to use tr-remote.
It also features options to make common tr-remote tasks much quicker to type, like the
.Fl t
switch, which allows you to pass an option to a torrent without the dash before the flag.
This simple shorthand makes using common commands like
.Dl transmission-remote Fl t Ar ID Fl i
much less tedious on the day-to-day.
.Pp
The other goal of
.Nm
is to provide statistical information about torrents in a clean fashion.
An example of this need is when the user would like to view information about the upload rates of the torrents currently seeding.
.Xr transmission-remote 1
indeed provides a way to get this with the `-t all -l' sequence, but it is more information than needed, and the format is unwieldy.
To combat this issue,
.Nm
has the
.Fl sul
switch to display the name and upload rate of seeding torrents in a clean format.
.Nm
also has the nifty feature to display torrent information from a set of tracker URLs.
To achieve this, you define an alias that binds to one or more tracker URLs in the
.Pa tracker
file distributed with
.Nm .
See
.Pa README
for more information.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h Ar HOST:PORT
Set the host and-or port that
.Xr transmission-remote 1
will attempt to connect to.
You may set either the
.Ar HOST
or
.Ar PORT
options separately, or both with the colon format.
You may NOT separate them with a space.
The default may be set in the HOSTPORT variable in the
.Pa tropriv.sh
file.
.It Fl a Ar USER:PASS
Set the user-name and password that
.Xr transmission-remote 1
will attempt to connect with.
The default may be set in the AUTH variable in the
.Pa tropriv.sh
file.
.It Fl p Ar options ...
Pass flags directly to
.Xr transmission-remote 1 .
All successive flags will be interpreted as
.Xr transmission-remote 1
flags.
No
.Nm
options may be supplied after this flag.
.It Fl m Ar base Op Ar new-base
Move all the torrents whose directories start with
.Ar base
to
.Ar new-base .
The
.Ar base
is the beginning of the path of any matching torrents location as stored in the Transmission session's records.
This may be the absolute path that the torrents file(s) are stored in, or a relative path to the current working directory of where your Transmission session was invoked (generally $HOME).
For example, the torrent with the ID 1 may have it's location stored in Transmission as `dir1/dir2'.
Because this is not an absolute path, (ie. the path doesn't start with `/') Transmission will internally append the CWD in which it was started in.
Let's say that Transmission was started in $HOME which expands to /home/user.
Torrent 1 will then be seen as being in $HOME/dir1/dir2, or /home/user/dir1/dir2.
This is good when you have to move your torrents to a new user's home path, because you don't have to change the base directory of the torrents.
But what if you do have torrents with a hard-coded $HOME, or an otherwise undesirable base path?
If you have hundreds of hard-coded torrents whose locations have changed from /home/user/ to a different user's $HOME, /home/user2, moving each file's location in Transmission can be tedious.
.Fl m
was designed to move torrents like these to a new base easily.
To aid with the example, to move all torrents whose base is stored as /home/user/ to /home/user2, the following command sequence would be used:
.Dl trop -m /home/user /home/user2
Now, all torrents with the base /home/user/ have been updated to point to /home/user2/.
If you omit
.Ar new-base ,
all matching torrents'
.Ar base
will be stripped from their location.
One important thing to note is that currently if you attempt to remove the base and the resulting relative path is still the same Transmission will _not_ update it to the relative path. However, once you do move the base, you can strip it to a relative path and not have to fuss if you move bases again.
.It Fl tm Ar tracker-alias
Fuctionally equivalent to
.Fl m
but filter out torrents not matching the trackers listed under
.Ar tracker-alias
.It Fl dl
Show information about downloading torrents.
This will include torrents that are both `uploading' and `downloading' information.
.It Fl tdl Ar tracker-alias
Fuctionally equivalent to
.Fl dl
but filter out torrents not matching the trackers listed under
.Ar tracker-alias
.It Fl ns
List number of torrents seeding.
This does NOT include torrents that are both `uploading' and `downloading' information.
.It Fl tns Ar tracker-alias
Fuctionally equivalent to
.Fl ns
but filter out torrents not matching the trackers listed under
.Ar tracker-alias
.It Fl si
Show information about seeding torrents.
This flag will display all information about each seeding torrent (equivalent to `-t id -i' in tr-remote).
.It Fl sul
List seeding torrents and their upload rates.
This flag will display the `Name' and `Upload' lines in a tabular format.
.It Fl ta Op Ar tracker-alias
Add a tracker alias to the
.Pa tracker
file interactively.
This option will ask the user to enter a tracker alias, the primary tracker to be associated with this alias, whether or not to add any secondary trackers and how many, then each secondary tracker on separate lines.
.It Fl tul Ar tracker-alias
Functionally equivalent to the
.Fl si
flag, but gets seeding torrents by tracker-alias.
.It Fl ts Ar tracker-alias
List information about seeding torrents by tracker-alias. The information is more terse than that of
.Fl si ,
this is intentional;
This switch was designed to filter out tracker-specific torrents in
.Fl si ,
and get more information about a specific torrent from this output.
.It Fl tt Ar tracker-alias
Show the total amount downloaded from a tracker set as seen by the trackers (free-leech downloads are not included).
.It Fl t Ar ID Ar option
Pass an option to a torrent.
The option to supply is any valid option coupled with the tr-remote `-t' switch, however, the leading dashes are removed.
.It Fl td Ar ID Ar action
Add torrent to a queue that will perform
.Ar action
when it completes.
.Ar action
is any valid option coupled with the tr-remote `-t' switch, however the leading dashes _must_ be removed.
This is the same format as the
.Fl t
switch.
The variables ADD_TRACKER_DONE and ADD_TRACKER_DONE_ACT in
.Pa trop.conf
are used to control the behavior of this command.
See
.Pa README
for more information.
.It Fl notd
Stop torrent from being added to the torrent-done queue if torrents are automatically being added with the ADD_TORRENT_DONE option in
.Pa trop.conf .
.It Fl terr
Show the name, ID, location and error field of torrents that show signs of an error.
.Nm
will warn the user if it detects a torrent error.
.It Fl tdel Ar tracker-alias
Remove
.Ar tracker-alias
from the
.Pa trackers
file.
.It Fl tl Op Ar tracker-alias
Show all the tracker URLs that are binded to
.Ar tracker-alias .
If no argument is supplied,
.Nm
will display all tracker-aliases and their tracker URLs.
.It Fl startup
Initialize
.Nm
defaults upon login. See
.Pa README
for more information.
.It Fl q
Suppress all message output from
.Nm .
.It Fl V Fl version
Show version information.
This includes the latest
.Xr transmission-remote 1
version that
.Nm
was tested against.
.It Fl help
Print a short description of the options on the command-line.
.Sh EXAMPLES
Show details about the torrent with the ID 1:
.Pp
.Dl "trop -t1 i"
.Pp
Add a tracker alias named 'demonii':
.Pp
.Dl "trop -ta demonii"
.Pp
Show the upload rates of torrents under the 'demonii' alias:
.Pp
.Dl "trop -tul demonii"
.Pp
Supply the host and authorization information on the command-line:
.Pp
.Dl "trop -h example.org:6789 -a bob:secretpass -sul"
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev HOSTPORT
Host that transmission-remote uses to connect to the RPC session.
.It Ev AUTH
Authorization information
.Xr transmission-remote 1
uses to connect to the RPC session.
.It Ev TROP_TRACKER
Contains the path to the
.Nm
AWK file.
.It Ev LC_ALL
.Nm
sets the locale variables to `POSIX'.
.Sh FILES
.Bl -tag -width Fl -compact
.It Pa install.sh
.Nm
installation script.
.It Pa trop.sh
Main program script.
.It Pa trop.conf
Configuration file.
.It Pa trop_torrent_done.sh
Glue file that Transmission runs upon torrent completion.
.It Pa tropriv.sh
Used to store private user information.
.It Pa trop.awk
AWK script used for various
.Nm
procedures.
.It Pa trackers
Contains the tracker alias definitions.
.Sh AUTHORS
.An -nosplit
.An bkazemi <bkazemi@users.sf.net>
.Sh SEE ALSO
.Xr transmission-remote 1
